---
  - name: install dependecies
    apt: name={{ item }} state=present
    with_items:
      - git
      - build-essential
      - libxslt-dev
      - python-dev
      - python-virtualenv
      - python-babel
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - nginx
